### PR TITLE
Added support for sprockets v3

### PR DESCRIPTION
**Pull request by bjarosze**
I've added support for sprockets v3 (tested on 3.2). I've also kept backwards compability.

### CODE REVIEW

**Comment by alchapone** [comment]
Great! will test and merge asap

**Comment by piyushchauhan2011** [comment]
:+1:  really needed it.

**Comment by piyushchauhan2011** [comment]
Can we merge this ? @alchapone

**Comment by alchapone** [comment]
@piyushchauhan2011 You can use `master` version for now

**Comment by piyushchauhan2011** [comment]
:+1:  @alchapone

**Pull request merged**
